### ISSUE TITLE
Issue: due Flag Not Functioning as Expected

### ISSUE THREAD

**Issue by Daemon-AT4** [gammons/ultralist#272]
---

### Issue: `due` Flag Not Functioning as Expected

**Description:**

I am experiencing an issue with the `due` flag in Ultralist. When I attempt to add a due date to a task using the `due` flag, the due date does not appear as expected.

**Steps to Reproduce:**

1. Run the following command to add a task with a due date:

    ```bash
    ultralist add "Learn how to conduct a Phishing Campaign +TCM-Security due:tom"
    ```

2. List all tasks to verify the due date:

    ```bash
    ultralist l
    ```

**Expected Behavior:**

The task should be added with the specified due date. For example:

```
all
1  [ ]  Tomorrow  Learn how to conduct a Phishing Campaign +TCM-Security 
```

**Actual Behavior:**

The task is added, but the due date is not displayed:

```
all
1  [ ]    Learn how to conduct a Phishing Campaign +TCM-Security
2  [ ]    Learn how to conduct a Phishing Campaign +TCM-Security
```

**System Information:**

- **Operating System:** Linux Mint

**Additional Context:**

This issue persists regardless of the due date format (e.g., `due:tom`, `due:sep1`, `due:2023-09-01`). I have also tried enclosing the task description and due date in quotes, but the due date still does not appear.

Any assistance in resolving this issue would be greatly appreciated.

Thank you!

**Comment by 00xNetrunner** [comment]
Dunno how, but it seems to work now,
